### ISSUE TITLE
Adding documentation to our project

### ISSUE THREAD

**Issue by TheFatPanda97** [utmmcss/mcss-website-frontend#10]
Currently, we mainly rely on discord to communicate technical processes and decisions. The purpose of this issue is to discuss whether this is necessary and if so, what are some of the possible solutions.

Some possible libraries for documentation:
- [Bookstack](https://www.bookstackapp.com/)
- [Vuepress](https://vuepress.vuejs.org/)

Library for documenting react components
- [Storybook](https://storybook.js.org/)

**Comment by lx1922** [comment]
I would say documentation will only be useful if we think the website will be reused by other people. But at the same time it will also help succeeding associates to refer for future changes.

Sort of 50 50. If we do go for it Book Stack seems good.

**Comment by nigow** [comment]
I'm inclined to think discord conversation is enough. While I understand the advantages of professional documentation, I'm afraid conversation would go all over considering the size of the team. 

We might as well make another (or two) discord channels for specific use cases (e.g. similar to #announcement but the directors can make announcements specifically to the tech team related to recent updates). I suppose this is slightly less professional, but I would prefer more centralized communication.

**Comment by lx1922** [comment]
> I'm inclined to think discord conversation is enough. While I understand the advantages of professional documentation, I'm afraid conversation would go all over considering the size of the team. 
> 
> We might as well make another (or two) discord channels for specific use cases (e.g. similar to #announcement but the directors can make announcements specifically to the tech team related to recent updates). I suppose this is slightly less professional, but I would prefer more centralized communication. 

Wouldn't Documentation also help future associates understand why we did something?

**Comment by nigow** [comment]
I'm skeptical that future associates/directors would need to know each of our decision process. If necessary, a good commit message would suffice that purpose.

**Comment by lx1922** [comment]
> I'm skeptical that future associates/directors would need to know each of our decision process. If necessary, a good commit message would suffice that purpose. 

That's true! I can't deny that.

**Comment by NerajM** [comment]
I agree with Tairi in that I think that discord communication is sufficient for a team of this size

**Comment by TheFatPanda97** [comment]
Okay, so after looking at everyone's opinions, we have decided to not implement a docs website, but instead, we will have specific channels for different issues.
