### ISSUE TITLE
[SPIKE] Investigate open source tools for scraping instagram content analytics

### ISSUE THREAD

**Issue by nxabdullah** [utmmcss/mcss-website-frontend#101]
### What?
Investigate open source scraping tools to help collect various analytics from instagram posts & stories.

### Outcome
We have an open source tool that can get the job done for us **OR** we can start planning on creating such tool. 
Also investigate instagram API to see if it is viable to create our own tool. 

### Notes / References
> The marketing team is wondering whether it may be possible to create some sort of scraping tool that would help  collect the number of likes, comments, shares on the posts and stories. We want to be able to use this tool to analyze data and strengthen our marketing approaches. 
[(Link to message)](https://discord.com/channels/1119339417212043335/1144749192372301905/1284571691942678593)

**Comment by MusaKhan16** [comment]
While I was not able to find open source tools as of yet, I found some free alternatives online. 

While NotJustAnalytics is pretty good, I recommend checking the others too see if they have some features that you are looking for which NotJustAnalytics may not cover.

Current free alternatives:
- [NotJustAnalytics](https://www.notjustanalytics.com/) ~ Most comprehensive so far
- [Instrack](https://instrack.app/instagram/utmmcss)
- [Toolzu](https://toolzu.com/profile-analyzer/instagram/)
- [Inflact](https://inflact.com/tools/profile-analyzer/?profile=utmmcss) ~ Some locked features

**Comment by nuhgooyin** [comment]
As Abdullah mentioned already, there are two possible approaches:
1. Use an existing (most likely paid) tool (like the ones Musa shared already)
2. Develop our own

For option 2, there are a couple of ways we can do this:
1. Use selenium (or puppeteer) to create a bot that can login, retrieve the data we need (e.x. likes, comments, shares), and then store it somewhere (e.x a shared Google Spreadsheet). We can then use Google Apps Script to run our bot periodically.
2. I skimmed the Instagram Graph API and basic API, which allow retrieval of likes on posts/stories. So we can try making a simple dashboard website for this (we can use a database to store metrics over time, and webhooks to update statistics (although not technically necessary to have a db)).

We'll most likely go with option 2 here^

If the marketing team wants additional features outside of the IG API (like tracking incoming and outgoing dms), we'll have to scrape it or use a private API like https://github.com/subzeroid/instagrapi (never used this one before so not sure how viable it is; possible sus).
