### ISSUE TITLE
Add New Frontpage Sponsors Section

### ISSUE THREAD

**Issue by eruditeme** [utmmcss/mcss-website-frontend#92]
> We want to display sponsors on our frontpage in the `/Sponsors` url

# Acceptance Criteria

- [x] Display grid of sponsor cards on the frontpage, linking the images to their url (like blogs pages)
- [x] clicking a sponsor will have their data shown w description, etc... (like blogs/{id} pages)
- [x] use react query for to make `useSponsorsList` and `useSponsorsGet` hooks

**Comment by eruditeme** [comment]
Just to confirm, the sponsors is going to be an element like blogs and events in the navbar right? Also I realized my sponsors was actually finished, should I still adjust it with the new react query hooks?

**Comment by anthonytedja** [comment]
yes thats right so there will be a mcss.club/sponsors page and mcss.club/sponsors/{id} page

**Comment by eruditeme** [comment]
I'm getting this error from api/client.ts.
<img width="694" alt="Screen Shot 2023-11-01 at 1 05 10 AM" src="https://github.com/utmmcss/mcss-website-frontend/assets/90787255/90ad587b-0da9-417a-badd-a3ed77eec63c">

**Comment by anthonytedja** [comment]
uh try `yarn install` or restart your code editor?

**Comment by eruditeme** [comment]
Still doesn't work TT Also when i open local host 3000 i get this error
<img width="596" alt="Screen Shot 2023-11-01 at 2 13 20 AM" src="https://github.com/utmmcss/mcss-website-frontend/assets/90787255/c66f6d21-5ede-4b0a-b018-8d7c88c704ec">
