### ISSUE TITLE
Replace logo with deer logo

### ISSUE THREAD

**Issue by HenrikSZ** [utmmcss/mcss-website-frontend#96]
On the top left of https://mcss.club/, replace the logo there with our official logo. You can use this version:

https://www.utm.utoronto.ca/math-cs-stats/sites/files/math-cs-stats/styles/full_width_m/public/shared/MCSS.png.webp?itok=GbZS_1hA

**Comment by MusaKhan16** [comment]
I can take on this task, I have already forked the repository and made changes to mine with the new logo, ready for a pull request. However, I wanted to mention that the logo is not aligned with the main content and that it follows the design of the old page. And if interested I can change the alignment.

I also wanted to know if we were going to redesign the website as a whole or, keep it pretty much the same and edit things around?

![image](https://github.com/user-attachments/assets/0a4b49f0-7e29-4dc2-bb0b-639b37d7d67e)
![image](https://github.com/user-attachments/assets/f9b3b9be-c71d-484d-810f-3f64cf8af652)

**Comment by HenrikSZ** [comment]
Maybe it is possible to do a color adjustment of our logo. I will pitch that to the marketing team! Thanks for noticing!

**Comment by MusaKhan16** [comment]
**Update:**
The new logo is being made by the marketing team and will be proposed soon, if it gets approved Ill update the site otherwise Ill revert to the initial logo we wanted to use.
